### ISSUE TITLE
Fails to build on arch linux due to SPIRV_WERROR=ON

### ISSUE THREAD

**Issue by rukai** [google/shaderc-rs#25]
Fails to build on arch linux.
Setting SPIRV_WERROR=OFF fixes the issue.
I'm guessing this hasn't affected others because arch has a more recent compiler? (GCC 8.2.0-2)

Strangely I cant reproduce the issue when building the latest known good shaderc. I tried using the commits in the shaderc-rs submodules with just shaderc but that succeeded as well.

I think it would make sense to set SPIRV_WERROR=OFF in the build.rs file as the compiler adding new warnings shouldn't break compilation. I'm guessing C++ compilers can just add warnings whenever they want?
```
--- stderr
/home/rubic/Projects/Crates/shaderc-rs/build/spirv-tools/utils/update_build_version.py:91: DeprecationWarning: 'U' mode is deprecated
  with open(changes_file, mode='rU') as f:
/home/rubic/Projects/Crates/shaderc-rs/build/spirv-tools/utils/update_build_version.py:91: DeprecationWarning: 'U' mode is deprecated
  with open(changes_file, mode='rU') as f:
/home/rubic/Projects/Crates/shaderc-rs/build/spirv-tools/source/text_handler.cpp: In member function ‘spv_result_t spvtools::AssemblyContext::binaryEncodeString(const char*, spv_instruction_t*)’:
/home/rubic/Projects/Crates/shaderc-rs/build/spirv-tools/source/text_handler.cpp:316:10: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
   strncpy(dest, value, length);
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/rubic/Projects/Crates/shaderc-rs/build/spirv-tools/source/text_handler.cpp:298:31: note: length computed here
   const size_t length = strlen(value);
                         ~~~~~~^~~~~~~
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-self-assign’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [spirv-tools/source/CMakeFiles/SPIRV-Tools.dir/build.make:484: spirv-tools/source/CMakeFiles/SPIRV-Tools.dir/text_handler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:375: spirv-tools/source/CMakeFiles/SPIRV-Tools.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/rubic/Projects/Crates/shaderc-rs/build/spirv-tools/source/text_handler.cpp: In member function ‘spv_result_t spvtools::AssemblyContext::binaryEncodeString(const char*, spv_instruction_t*)’:
/home/rubic/Projects/Crates/shaderc-rs/build/spirv-tools/source/text_handler.cpp:316:10: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
   strncpy(dest, value, length);
   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/home/rubic/Projects/Crates/shaderc-rs/build/spirv-tools/source/text_handler.cpp:298:31: note: length computed here
   const size_t length = strlen(value);
                         ~~~~~~^~~~~~~
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-self-assign’ [-Werror]
cc1plus: all warnings being treated as errors
make[2]: *** [spirv-tools/source/CMakeFiles/SPIRV-Tools-shared.dir/build.make:484: spirv-tools/source/CMakeFiles/SPIRV-Tools-shared.dir/text_handler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:636: spirv-tools/source/CMakeFiles/SPIRV-Tools-shared.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.33/src/lib.rs:773:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: cmake::fail
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.33/src/lib.rs:773
   7: cmake::run
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.33/src/lib.rs:754
   8: cmake::Config::build
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.33/src/lib.rs:666
   9: build_script_build::build_shaderc
             at build/build.rs:21
  10: build_script_build::main
             at build/build.rs:62
  11: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by antiagainst** [comment]
That is reasonable. I turned off `SPIRV_WERROR` in `build.rs`. Please have a try and let me know whether it works for you.

**Comment by rukai** [comment]
Yes, that fixes it! thank you.

**Comment by antiagainst** [comment]
OKay, I'll cut a new release then.
